const vi = {
  quantity: 'Số lượng',
  retry: 'Tải lại trạng thái',
  resolved: 'Đã xử lý',
  replacement: 'Đã đổi sản phẩm',
  refund: 'Đã hoàn tiền thủ công',
  title: 'Yêu cầu đổi trả',
  reason: 'Lý do',
  description: 'Mô tả vấn đề',
  video: 'Video khui hàng liên tục',
  confirm: 'Tôi xác nhận video quay liên tục từ lúc khui hàng.',
  submit: 'Gửi yêu cầu',
  loading: 'Đang xử lý…',
  disabled: 'Tải video đổi trả chưa được mở. Vui lòng liên hệ cửa hàng.',
  error: 'Không thể xử lý yêu cầu. Vui lòng kiểm tra video và thử lại.',
  requested: 'Chờ duyệt',
  approved: 'Đã duyệt — cửa hàng sẽ liên hệ để xử lý',
  rejected: 'Từ chối',
  manufacturing_defect: 'Lỗi sản xuất',
  shipping_damage: 'Hỏng khi vận chuyển',
  wrong_item: 'Giao sai hàng',
  limit: 'Giới hạn video',
  success: 'Đã gửi yêu cầu. Cửa hàng sẽ xem xét video và phản hồi.',
}
const en = {
  quantity: 'Quantity',
  retry: 'Reload status',
  resolved: 'Resolved',
  replacement: 'Replacement completed',
  refund: 'Refund completed manually',
  title: 'Return request',
  reason: 'Reason',
  description: 'Describe the problem',
  video: 'Continuous unboxing video',
  confirm: 'I confirm this video continuously records the unboxing.',
  submit: 'Submit request',
  loading: 'Processing…',
  disabled: 'Return video uploads are not yet enabled. Please contact the store.',
  error: 'Unable to process your request. Check the video and try again.',
  requested: 'Awaiting review',
  approved: 'Approved — the store will contact you',
  rejected: 'Rejected',
  manufacturing_defect: 'Manufacturing defect',
  shipping_damage: 'Shipping damage',
  wrong_item: 'Wrong item',
  limit: 'Video limit',
  success: 'Request submitted. The store will review your video and respond.',
}
const zh = {
  quantity: '数量',
  retry: '重新加载状态',
  resolved: '已处理',
  replacement: '已更换商品',
  refund: '已手动退款',
  title: '退换货申请',
  reason: '原因',
  description: '描述问题',
  video: '连续开箱视频',
  confirm: '我确认视频从开箱开始连续拍摄。',
  submit: '提交申请',
  loading: '处理中…',
  disabled: '退换货视频上传尚未启用。请联系商店。',
  error: '无法处理申请。请检查视频并重试。',
  requested: '等待审核',
  approved: '已批准 — 商店将联系您',
  rejected: '已拒绝',
  manufacturing_defect: '制造缺陷',
  shipping_damage: '运输损坏',
  wrong_item: '发错商品',
  limit: '视频限制',
  success: '申请已提交。商店将审核视频并回复。',
}
export const returnStrings = (lang) => ({ vi, en, zh })[lang] ?? vi
