// D-48: giao diện admin chỉ tiếng Việt. Nội dung sản phẩm/FAQ/lô vẫn nhập đủ vi/en/zh.
export const S = {
  title: 'Quản trị LAMVI',
  nav: { products: 'Sản phẩm', faq: 'Hỏi đáp', batches: 'Lô đèn', may: 'Mây (AI)', it: 'Dashboard IT →', site: '← Về trang web' },
  common: {
    loading: 'Đang tải…',
    save: 'Lưu',
    saving: 'Đang lưu…',
    saved: 'Đã lưu.',
    create: 'Thêm mới',
    edit: 'Sửa',
    cancel: 'Huỷ',
    delete: 'Xoá',
    confirmDelete: 'Xoá mục này? Không thể hoàn tác.',
    sortOrder: 'Thứ tự hiển thị',
    empty: 'Chưa có dữ liệu.',
    forbiddenTitle: 'Không có quyền truy cập',
    forbiddenText: 'Tài khoản này không phải admin/IT. Quyền được cấp trong Supabase (bảng profiles, cột role).',
    langs: { vi: 'Tiếng Việt', en: 'English', zh: '简体中文' },
    viRequiredHint: 'Tiếng Việt bắt buộc; thiếu bản en/zh thì web hiện tiếng Việt (D-40).',
  },
  products: {
    title: 'Sản phẩm',
    slug: 'Slug (đường dẫn)',
    slugHint: 'Chữ thường không dấu, số, gạch nối. Ví dụ: den-nguyet',
    kind: 'Loại',
    kinds: { single: 'Đèn đơn', set: 'Bộ đèn' },
    status: 'Trạng thái',
    statuses: { draft: 'Nháp', published: 'Đang bán', hidden: 'Đã ẩn' },
    statusHint: 'Chỉ sản phẩm "Đang bán" hiển thị với khách (D-39).',
    price: 'Giá bán đã gồm VAT (VND)',
    tone: 'Màu minh hoạ',
    tones: { '': '— Mặc định —', amber: 'Hổ phách', dusk: 'Hoàng hôn', dawn: 'Bình minh', moss: 'Trầm mộc' },
    name: 'Tên sản phẩm',
    description: 'Mô tả',
    badge: 'Nhãn (vd "Bán chạy")',
    colName: 'Tên',
    colPrice: 'Giá (đã VAT)',
    colStatus: 'Trạng thái',
    colImage: 'Ảnh',
    image: 'Ảnh sản phẩm',
    imageHint: 'JPG, PNG hoặc WebP, tối đa {mb} MB. Ảnh vuông hiển thị đẹp nhất. Chưa có ảnh thì web dùng hình đèn minh hoạ.',
    imageAlt: 'Chú thích ảnh (alt)',
    imageAltHint: 'Mô tả ngắn cho người dùng trình đọc màn hình và cho công cụ tìm kiếm. Bỏ trống thì dùng tên sản phẩm.',
    chooseImage: 'Chọn ảnh…',
    replaceImage: 'Đổi ảnh…',
    removeImage: 'Gỡ ảnh',
    confirmRemoveImage: 'Gỡ ảnh này? Web sẽ quay về hình đèn minh hoạ.',
    noImage: 'Chưa có ảnh — web đang dùng hình đèn minh hoạ.',
    uploadingImage: 'Đang tải ảnh… {percent}%',
    imageSaved: 'Đã cập nhật ảnh.',
    saveFirst: 'Lưu sản phẩm trước rồi mới tải ảnh lên được.',
    hasImage: 'Có',
  },
  faq: {
    title: 'Hỏi đáp (FAQ)',
    question: 'Câu hỏi',
    answer: 'Trả lời',
    published: 'Hiển thị trên web',
    note: 'Mây đọc FAQ này để trả lời khách — chỉ ghi thông tin chính xác.',
    colQuestion: 'Câu hỏi',
    colPublished: 'Hiển thị',
    yes: 'Có',
    no: 'Không',
  },
  may: {
    title: 'Cấu hình Mây',
    usageTitle: 'Chi phí OpenAI tháng này',
    usage: '{cost} / {budget} USD ({pct}%) — {requests} lượt gọi',
    alertWarning: 'Đã dùng trên 80% ngân sách tháng.',
    alertExhausted: 'Đã hết ngân sách tháng — Mây đang ở chế độ FAQ offline.',
    notConfigured: 'Server chưa có khoá OpenAI (OPENAI_API_KEY) — Mây luôn chạy chế độ FAQ offline.',
    openai: 'Bật trả lời bằng OpenAI',
    openaiHint:
      'Mặc định bật (D-67, I-14 đã duyệt). Khi tắt, Mây trả lời bằng FAQ offline. Mây không bao giờ gửi SĐT/email sang OpenAI.',
    budget: 'Ngân sách tháng (USD)',
    budgetHint: '80% → cảnh báo; 100% → chuyển FAQ offline (§22.4).',
    channel: 'Kênh hỗ trợ người thật (Q-31, D-56)',
    channelHint: 'Ví dụ "Zalo 0900 000 000" hoặc "hotro@moc.vn". Để trống thì Mây không gợi ý kênh.',
    limits: 'Hạn mức tin nhắn (§22.4)',
    guestPerSession: 'Vãng lai — tin / phiên',
    guestPerDayIp: 'Vãng lai — tin / ngày / IP',
    userPerDay: 'Đã đăng nhập — tin / ngày',
    maxChars: 'Độ dài tối đa (ký tự)',
    messages: 'Câu thông báo (mỗi dòng một câu, chọn ngẫu nhiên)',
    groups: {
      sick: 'OpenAI lỗi / quá 15 giây ("ốm")',
      tired: 'Hết lượt ("mệt")',
      resting: 'FAQ offline ("nghỉ ngơi")',
      unknown: 'Không biết — có kênh hỗ trợ (dùng {channel})',
      unknownNoChannel: 'Không biết — chưa có kênh hỗ trợ',
    },
  },
  batches: {
    title: 'Lô đèn & video lô',
    code: 'Mã lô (in trên QR khắc đèn)',
    codeHint: 'Chữ in hoa, số, gạch nối. Không đổi được sau khi xuất bản.',
    producedOn: 'Ngày làm',
    batchTitle: 'Tiêu đề',
    story: 'Câu chuyện lô',
    status: 'Trạng thái',
    statuses: { created: 'Chưa xuất bản', video_published: 'Đã xuất bản' },
    video: 'Video lô',
    noVideo: 'Chưa có video.',
    chooseVideo: 'Chọn video (MP4, WebM, MOV)',
    replaceVideo: 'Thay video',
    uploading: 'Đang tải lên… {percent}%',
    uploaded: 'Đã tải video lên.',
    publish: 'Xuất bản',
    publishConfirm: 'Xuất bản lô này? Sau khi xuất bản không thể gỡ, không xoá được lô và không đổi được mã lô (D-47).',
    published: 'Lô đã xuất bản — trang QR công khai tại {url}. Được thay video, không gỡ/xoá (D-47).',
    qrUrl: 'Link QR',
    colCode: 'Mã lô',
    colDate: 'Ngày làm',
    colStatus: 'Trạng thái',
    colVideo: 'Video',
    hasVideo: 'Có',
  },
}

export const fmt = (s, vars) => s.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? m)
