// D-48: giao diện admin chỉ tiếng Việt. Nội dung sản phẩm/FAQ/lô vẫn nhập đủ vi/en/zh.
export const S = {
  title: 'Quản trị MỘC',
  nav: { orders: 'Đơn hàng', coupons: 'Mã giảm giá', shop: 'Phí ship & COD', products: 'Sản phẩm', faq: 'Hỏi đáp', batches: 'Lô đèn', may: 'Mây (AI)', it: 'Dashboard IT →', site: '← Về trang web' },
  common: {
    loading: 'Đang tải…',
    save: 'Lưu',
    saving: 'Đang lưu…',
    saved: 'Đã lưu.',
    create: 'Thêm mới',
    edit: 'Sửa',
    cancel: 'Huỷ',
    delete: 'Xoá',
    confirmDelete: 'Xoá mục này? Không thể hoàn tác.',
    sortOrder: 'Thứ tự hiển thị',
    empty: 'Chưa có dữ liệu.',
    forbiddenTitle: 'Không có quyền truy cập',
    forbiddenText: 'Tài khoản này không phải admin/IT. Quyền được cấp trong Supabase (bảng profiles, cột role).',
    langs: { vi: 'Tiếng Việt', en: 'English', zh: '简体中文' },
    viRequiredHint: 'Tiếng Việt bắt buộc; thiếu bản en/zh thì web hiện tiếng Việt (D-40).',
  },
  products: {
    title: 'Sản phẩm',
    slug: 'Slug (đường dẫn)',
    slugHint: 'Chữ thường không dấu, số, gạch nối. Ví dụ: den-nguyet',
    kind: 'Loại',
    kinds: { single: 'Đèn đơn', set: 'Bộ đèn' },
    status: 'Trạng thái',
    statuses: { draft: 'Nháp', published: 'Đang bán', hidden: 'Đã ẩn' },
    statusHint: 'Chỉ sản phẩm "Đang bán" hiển thị với khách (D-39).',
    price: 'Giá chưa VAT (VND)',
    tone: 'Màu minh hoạ',
    tones: { '': '— Mặc định —', amber: 'Hổ phách', dusk: 'Hoàng hôn', dawn: 'Bình minh', moss: 'Trầm mộc' },
    name: 'Tên sản phẩm',
    description: 'Mô tả',
    badge: 'Nhãn (vd "Bán chạy")',
    colName: 'Tên',
    colPrice: 'Giá chưa VAT',
    colStatus: 'Trạng thái',
  },
  faq: {
    title: 'Hỏi đáp (FAQ)',
    question: 'Câu hỏi',
    answer: 'Trả lời',
    published: 'Hiển thị trên web',
    note: 'Mây đọc FAQ này để trả lời khách — chỉ ghi thông tin chính xác.',
    colQuestion: 'Câu hỏi',
    colPublished: 'Hiển thị',
    yes: 'Có',
    no: 'Không',
  },
  orders: {
    title: 'Đơn hàng',
    filterAll: 'Tất cả',
    filterFlagged: 'Cần xử lý tiền',
    colCode: 'Mã đơn',
    colDate: 'Ngày đặt',
    colRecipient: 'Người nhận',
    colTotal: 'Tổng',
    colStatus: 'Trạng thái',
    colPayment: 'Thanh toán',
    back: '← Danh sách đơn',
    detail: 'Đơn #{code}',
    buyer: 'Người mua',
    recipient: 'Người nhận',
    type: { gift: 'Mua tặng', self: 'Mua cho mình' },
    message: 'Có lời chúc — trang QR bằng {lang}',
    noMessage: 'Không có lời chúc',
    items: 'Dòng hàng',
    batch: 'Lô',
    noBatch: '— Chưa gán —',
    batchUnpublished: '(chưa xuất bản video)',
    pricing: 'Giá',
    flags: { PAID_AFTER_CANCEL: 'Tiền về sau khi đơn đã huỷ — cần hoàn tiền', AMOUNT_MISMATCH: 'Số tiền nhận khác tổng đơn — cần hoàn tiền' },
    paidInfo: 'Đã nhận {amount} lúc {at} (mã GD {ref})',
    stage: 'Công đoạn',
    tracking: 'Mã vận đơn',
    refundAmount: 'Số tiền đã hoàn (VND)',
    refundNote: 'Ghi chú hoàn tiền (ngân hàng, ngày, mã GD…)',
    refundDone: 'Đã hoàn {amount} — {note}',
    confirmCancel: 'Huỷ đơn này? Đơn đã thanh toán sẽ chuyển sang chờ hoàn tiền.',
    shipHint: 'Chỉ gửi được khi mọi dòng hàng đã gán lô có video xuất bản (BR-ORD-002).',
    history: 'Lịch sử thay đổi',
    historyCols: { at: 'Thời điểm', who: 'Người thực hiện', action: 'Thao tác', change: 'Thay đổi' },
    roles: { customer: 'Khách', admin: 'Admin', it: 'IT', system: 'Hệ thống' },
    events: {
      create: 'Tạo đơn',
      payment_confirmed: 'Nhận thanh toán',
      payment_mismatch: 'Tiền về lệch số',
      paid_after_cancel: 'Tiền về sau khi huỷ',
      assign_batch: 'Gán lô',
    },
    actions: {
      start_production: 'Bắt đầu làm',
      set_stage: 'Cập nhật công đoạn',
      pack: 'Đã đóng gói',
      ship: 'Gửi hàng',
      set_tracking: 'Sửa mã vận đơn',
      deliver: 'Đã giao',
      delivery_failed: 'Giao thất bại',
      cancel: 'Huỷ đơn',
      cod_collected: 'Đã thu COD',
      refund: 'Ghi nhận đã hoàn tiền',
    },
  },
  coupons: {
    title: 'Mã giảm giá',
    code: 'Mã',
    codeHint: 'Chữ in hoa, số, gạch nối; khách nhập không phân biệt hoa thường.',
    status: 'Trạng thái',
    statuses: { active: 'Đang bật', inactive: 'Đã tắt' },
    type: 'Loại',
    types: { percent: 'Giảm %', amount: 'Giảm số tiền', free_shipping: 'Miễn phí ship' },
    value: 'Giá trị',
    valueHint: { percent: '1–100 (%)', amount: 'Số tiền VND', free_shipping: '' },
    maxDiscount: 'Giảm tối đa (VND, chỉ loại %)',
    minOrder: 'Tạm tính tối thiểu (VND)',
    startsAt: 'Bắt đầu',
    endsAt: 'Kết thúc',
    usageLimit: 'Tổng số lượt',
    perUserLimit: 'Số lượt mỗi khách',
    scope: 'Áp dụng cho',
    scopeAll: 'Toàn đơn',
    scopeProducts: 'Chỉ các sản phẩm đã chọn',
    note: 'Ghi chú nội bộ',
    optional: 'Để trống = không giới hạn',
    rules: 'Giảm giá trừ trước VAT, không trừ vào phí ship (D-65…D-68). Huỷ đơn trả lại lượt.',
    colUsed: 'Đã dùng',
    colValue: 'Giá trị',
    colWindow: 'Thời gian',
    maxShort: 'tối đa {amount}',
  },
  shop: {
    title: 'Phí vận chuyển & COD',
    shippingFee: 'Phí ship đồng giá (VND)',
    freeShippingFrom: 'Miễn phí ship khi tạm tính từ (VND)',
    freeHint: 'Để trống = không miễn phí theo mức.',
    codMaxTotal: 'Tổng đơn tối đa cho COD (VND)',
    codHint: 'Để trống = không giới hạn. COD luôn bị chặn khi giao cho người khác (BR-PAY-004).',
    vatNote: 'VAT 10% tính trên (tạm tính − giảm giá), không tính trên phí ship (D-62).',
  },
  may: {
    title: 'Cấu hình Mây',
    usageTitle: 'Chi phí OpenAI tháng này',
    usage: '{cost} / {budget} USD ({pct}%) — {requests} lượt gọi',
    alertWarning: 'Đã dùng trên 80% ngân sách tháng.',
    alertExhausted: 'Đã hết ngân sách tháng — Mây đang ở chế độ FAQ offline.',
    notConfigured: 'Server chưa có khoá OpenAI (OPENAI_API_KEY) — Mây luôn chạy chế độ FAQ offline.',
    openai: 'Bật trả lời bằng OpenAI',
    openaiHint:
      'D-55: chỉ bật khi pháp chế đã duyệt việc gửi nội dung chat sang OpenAI (I-14). Khi tắt, Mây trả lời bằng FAQ offline. Mây không bao giờ gửi SĐT/email sang OpenAI.',
    budget: 'Ngân sách tháng (USD)',
    budgetHint: '80% → cảnh báo; 100% → chuyển FAQ offline (§22.4).',
    channel: 'Kênh hỗ trợ người thật (Q-31, D-56)',
    channelHint: 'Ví dụ "Zalo 0900 000 000" hoặc "hotro@moc.vn". Để trống thì Mây không gợi ý kênh.',
    limits: 'Hạn mức tin nhắn (§22.4)',
    guestPerSession: 'Vãng lai — tin / phiên',
    guestPerDayIp: 'Vãng lai — tin / ngày / IP',
    userPerDay: 'Đã đăng nhập — tin / ngày',
    maxChars: 'Độ dài tối đa (ký tự)',
    messages: 'Câu thông báo (mỗi dòng một câu, chọn ngẫu nhiên)',
    groups: {
      sick: 'OpenAI lỗi / quá 15 giây ("ốm")',
      tired: 'Hết lượt ("mệt")',
      resting: 'FAQ offline ("nghỉ ngơi")',
      unknown: 'Không biết — có kênh hỗ trợ (dùng {channel})',
      unknownNoChannel: 'Không biết — chưa có kênh hỗ trợ',
    },
  },
  batches: {
    title: 'Lô đèn & video lô',
    code: 'Mã lô (in trên QR khắc đèn)',
    codeHint: 'Chữ in hoa, số, gạch nối. Không đổi được sau khi xuất bản.',
    producedOn: 'Ngày làm',
    batchTitle: 'Tiêu đề',
    story: 'Câu chuyện lô',
    status: 'Trạng thái',
    statuses: { created: 'Chưa xuất bản', video_published: 'Đã xuất bản' },
    video: 'Video lô',
    noVideo: 'Chưa có video.',
    chooseVideo: 'Chọn video (MP4, WebM, MOV)',
    replaceVideo: 'Thay video',
    uploading: 'Đang tải lên… {percent}%',
    uploaded: 'Đã tải video lên.',
    publish: 'Xuất bản',
    publishConfirm: 'Xuất bản lô này? Sau khi xuất bản không thể gỡ, không xoá được lô và không đổi được mã lô (D-47).',
    published: 'Lô đã xuất bản — trang QR công khai tại {url}. Được thay video, không gỡ/xoá (D-47).',
    qrUrl: 'Link QR',
    colCode: 'Mã lô',
    colDate: 'Ngày làm',
    colStatus: 'Trạng thái',
    colVideo: 'Video',
    hasVideo: 'Có',
  },
}

export const fmt = (s, vars) => s.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? m)
