// D-48: giao diện admin chỉ tiếng Việt. Nội dung sản phẩm/FAQ/lô vẫn nhập đủ vi/en/zh.
export const S = {
  title: 'Quản trị MỘC',
  nav: { products: 'Sản phẩm', faq: 'Hỏi đáp', batches: 'Lô đèn', it: 'Dashboard IT →', site: '← Về trang web' },
  common: {
    loading: 'Đang tải…',
    save: 'Lưu',
    saving: 'Đang lưu…',
    saved: 'Đã lưu.',
    create: 'Thêm mới',
    edit: 'Sửa',
    cancel: 'Huỷ',
    delete: 'Xoá',
    confirmDelete: 'Xoá mục này? Không thể hoàn tác.',
    sortOrder: 'Thứ tự hiển thị',
    empty: 'Chưa có dữ liệu.',
    forbiddenTitle: 'Không có quyền truy cập',
    forbiddenText: 'Tài khoản này không phải admin/IT. Quyền được cấp trong Supabase (bảng profiles, cột role).',
    langs: { vi: 'Tiếng Việt', en: 'English', zh: '简体中文' },
    viRequiredHint: 'Tiếng Việt bắt buộc; thiếu bản en/zh thì web hiện tiếng Việt (D-40).',
  },
  products: {
    title: 'Sản phẩm',
    slug: 'Slug (đường dẫn)',
    slugHint: 'Chữ thường không dấu, số, gạch nối. Ví dụ: den-nguyet',
    kind: 'Loại',
    kinds: { single: 'Đèn đơn', set: 'Bộ đèn' },
    status: 'Trạng thái',
    statuses: { draft: 'Nháp', published: 'Đang bán', hidden: 'Đã ẩn' },
    statusHint: 'Chỉ sản phẩm "Đang bán" hiển thị với khách (D-39).',
    price: 'Giá chưa VAT (VND)',
    tone: 'Màu minh hoạ',
    tones: { '': '— Mặc định —', amber: 'Hổ phách', dusk: 'Hoàng hôn', dawn: 'Bình minh', moss: 'Trầm mộc' },
    name: 'Tên sản phẩm',
    description: 'Mô tả',
    badge: 'Nhãn (vd "Bán chạy")',
    colName: 'Tên',
    colPrice: 'Giá chưa VAT',
    colStatus: 'Trạng thái',
  },
  faq: {
    title: 'Hỏi đáp (FAQ)',
    question: 'Câu hỏi',
    answer: 'Trả lời',
    published: 'Hiển thị trên web',
    note: 'Mây đọc FAQ này để trả lời khách — chỉ ghi thông tin chính xác.',
    colQuestion: 'Câu hỏi',
    colPublished: 'Hiển thị',
    yes: 'Có',
    no: 'Không',
  },
  batches: {
    title: 'Lô đèn & video lô',
    code: 'Mã lô (in trên QR khắc đèn)',
    codeHint: 'Chữ in hoa, số, gạch nối. Không đổi được sau khi xuất bản.',
    producedOn: 'Ngày làm',
    batchTitle: 'Tiêu đề',
    story: 'Câu chuyện lô',
    status: 'Trạng thái',
    statuses: { created: 'Chưa xuất bản', video_published: 'Đã xuất bản' },
    video: 'Video lô',
    noVideo: 'Chưa có video.',
    chooseVideo: 'Chọn video (MP4, WebM, MOV)',
    replaceVideo: 'Thay video',
    uploading: 'Đang tải lên… {percent}%',
    uploaded: 'Đã tải video lên.',
    publish: 'Xuất bản',
    publishConfirm: 'Xuất bản lô này? Sau khi xuất bản không thể gỡ, không xoá được lô và không đổi được mã lô (D-47).',
    published: 'Lô đã xuất bản — trang QR công khai tại {url}. Được thay video, không gỡ/xoá (D-47).',
    qrUrl: 'Link QR',
    colCode: 'Mã lô',
    colDate: 'Ngày làm',
    colStatus: 'Trạng thái',
    colVideo: 'Video',
    hasVideo: 'Có',
  },
}

export const fmt = (s, vars) => s.replace(/\{(\w+)\}/g, (m, k) => vars[k] ?? m)
